default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: favo_development

test:
  <<: *default
  database: favo_test

production:
  <<: *default
  database: favo_production
  username: favo
  password: <%= ENV['FAVO_DATABASE_PASSWORD'] %>
